// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADIe1uVqbLzg3jRAhAxPgolCRBMnv91ko',
    appId: '1:154072375713:web:255bd8068bbad4ac462be0',
    messagingSenderId: '154072375713',
    projectId: 'smart-room-finder-app-firebase',
    authDomain: 'smart-room-finder-app-firebase.firebaseapp.com',
    storageBucket: 'smart-room-finder-app-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeXHGaDXbotYlIMc1wVIiwzOpq2dES_Jc',
    appId: '1:154072375713:android:c281b06fa515de96462be0',
    messagingSenderId: '154072375713',
    projectId: 'smart-room-finder-app-firebase',
    storageBucket: 'smart-room-finder-app-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANimtvGvOsXGPT4Ie_kRaN7DCP4QpvDoY',
    appId: '1:154072375713:ios:1e4c39226db2c303462be0',
    messagingSenderId: '154072375713',
    projectId: 'smart-room-finder-app-firebase',
    storageBucket: 'smart-room-finder-app-firebase.firebasestorage.app',
    androidClientId: '154072375713-snru8hj1ra0dbf5pefr2jcet0u63i2h4.apps.googleusercontent.com',
    iosClientId: '154072375713-2kr93nqvgaupkojj7oetdu46jjqsf0tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRoomFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANimtvGvOsXGPT4Ie_kRaN7DCP4QpvDoY',
    appId: '1:154072375713:ios:1e4c39226db2c303462be0',
    messagingSenderId: '154072375713',
    projectId: 'smart-room-finder-app-firebase',
    storageBucket: 'smart-room-finder-app-firebase.firebasestorage.app',
    androidClientId: '154072375713-snru8hj1ra0dbf5pefr2jcet0u63i2h4.apps.googleusercontent.com',
    iosClientId: '154072375713-2kr93nqvgaupkojj7oetdu46jjqsf0tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRoomFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADIe1uVqbLzg3jRAhAxPgolCRBMnv91ko',
    appId: '1:154072375713:web:255bd8068bbad4ac462be0',
    messagingSenderId: '154072375713',
    projectId: 'smart-room-finder-app-firebase',
    authDomain: 'smart-room-finder-app-firebase.firebaseapp.com',
    storageBucket: 'smart-room-finder-app-firebase.firebasestorage.app',
  );

}